### ISSUE TITLE
Working with Instagram's API

### ISSUE THREAD

**Issue by phlco** [ChristopherJohnson25/FinalProject#1]
Have you registered an API key with Instagram and reviewed the documentation for the tag end point?

**Comment by ChristopherJohnson25** [comment]
Turns out the MagicSeaweed people are British, so they probably aren't working anymore due to the time difference. Will spend the rest of the afternoon on the Instagram docs and getting that going.

**Comment by ChristopherJohnson25** [comment]
Hey Phil, not sure what your schedule is like, but I'm having a MagicSeaweed API issue, it's giving me data and not throwing an error but the data is totally different than the simple JSON it's supposed to give. Maybe if you have a second you can look. Thanks

**Comment by ChristopherJohnson25** [comment]
Hey Phil, having a very strange issue with my API, could you help if you have anytime. All the sudden everything is undefined and the app is broken.

**Comment by phlco** [comment]
make sure you're more specifi it's very hard to tell where your problem is happening without further debugging. 

remember to console.log everything in your errors and responses.
