### ISSUE TITLE
Trouble with Semantic UI Modals

### ISSUE THREAD

**Issue by ChristopherJohnson25** [ChristopherJohnson25/FinalProject#4]
I'm using the Semantic UI modal and it works great, except for the fact that the modal div shows up on the page before you click the modal, then goes away after. A bit tough to explain...

The modal div starts on line22 of the Report.ejs file, and the javascript is on ln42 of main.js

Thanks

**Comment by sungchoi** [comment]
@ChristopherJohnson25 
What's a long modal? Did you mean large modal?

**Comment by sungchoi** [comment]
@ChristopherJohnson25 NM. I see that it's a scrollable modal.

**Comment by sungchoi** [comment]
@ChristopherJohnson25 
Are you getting any other errors?
Are you sure all of your front-end dependencies are being loaded properly?

**Comment by ChristopherJohnson25** [comment]
I fixed it sung!!
Thanks for your help.

**Comment by sungchoi** [comment]
@ChristopherJohnson25 
What was the problem? Did you forget the .ui class?
Were you missing a dependency?

**Comment by ChristopherJohnson25** [comment]
Forgot the UI class...:(. Now faced with new formatting issues, but can fix those on my own. thanks sung!
